name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
                    cache-dependency-path: 'package.json'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Lint, format, test
        run: npm run check
